services:
  backend:
    build: ./backend
    ports:
      - 8000:4370
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 60000
    volumes:
      - ./auth.json:/auth.json
      - ./test-data:/data
