services:
  backend:
    build: ./backend
    ports:
      - 4370:4370
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: 20m
      HTTPS: false
      ENABLE_USER_SIGNUP: true
      PORT: 4370
    volumes:
      - ./auth.json:/auth.json
      - ./test-data:/data
