services:
  tungsten-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./../mongodb:/mongodb

  tungsten-backend:
    build: .
    ports:
      - 4370:4370
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: 20m
      HTTPS: false
      ENABLE_USER_SIGNUP: true
    volumes:
      - ./../test-data:/data
