services:
  tungsten:
    build: .
    ports:
      - 4370:4370
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: 20m
      HTTPS: false
      ENABLE_USER_SIGNUP: true
    volumes:
      - ./../auth.json:/auth.json
      - ./../test-data:/data
